server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml
  kafka:
    bootstrap-servers: localhost:9092   # ← active 프로필에서 이 값이 실제로 로드되는지!
    producer:
      acks: all
      properties:
        enable.idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

  kafka:
    properties:
      auto:
        create.topics.enable: true

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false

# PG 시뮬레이터 연결 정보
pg:
  base-url: http://localhost:9090
  user-id: 135135
  callback-url: http://localhost:8080/api/v1/payments/callback

# OpenFeign 공통 설정
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000     # ms, TCP 연결 타임아웃
        readTimeout: 2500        # ms, 응답 타임아웃
        loggerLevel: basic       # none|basic|headers|full
        decode404: true          # 404를 예외 대신 정상 응답으로 디코드
      pgClient:                  # 특정 클라이언트(옵션): pg 전용 세부값
        connectTimeout: 1000
        readTimeout: 2500
        loggerLevel: basic

resilience4j:
  circuitbreaker:
    aspect-order: 1
    instances:
      pg:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
  retry:
    aspect-order: 2
    instances:
      pg:
        maxAttempts: 3
        waitDuration: 300ms
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException

logging:
  level:
    com.loopers.infrastructure.pg.PgFeignClient: DEBUG

payments:
  recon:
    fixed-delay: 30000
    batch-size: 200